# Generated by Django 4.1.1 on 2022-09-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Janta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='Bank_name',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='Email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='Full_Names',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='Gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='National_ID',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='Phone_no',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='writer',
            name='Bank_name',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='writer',
            name='Email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='writer',
            name='Full_Names',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='writer',
            name='Gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='writer',
            name='National_ID',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='writer',
            name='Phone_no',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
