# Generated by Django 4.1.1 on 2022-09-16 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Janta', '0003_manager_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=20, null=True)),
                ('cpp', models.CharField(max_length=10, null=True)),
                ('pages', models.IntegerField(null=True)),
                ('writer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Janta.writer')),
            ],
        ),
    ]
