# Generated by Django 4.1.1 on 2022-09-18 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Janta', '0005_order_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Janta.writer'),
        ),
    ]
