# Generated by Django 4.1.1 on 2022-09-19 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Janta', '0007_order_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='manager',
        ),
    ]
