# Generated by Django 4.1.1 on 2022-11-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Janta', '0009_order_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='profile_pic',
            field=models.ImageField(blank=True, default='avatar.png', null=True, upload_to=''),
        ),
    ]
